### ISSUE TITLE
Error trying to set flatpickr default language.

### ISSUE THREAD

**Issue by dsisconeto** [BRACKETS-by-TRIAD/craftable-frontend#14]
When I put the language of laravel as
pt-br, the following code snippet shows an error because flatpickr does not have a pt-br file.

`locale: userLanguage === 'en' ? null : require('flatpickr/dist/l10n/' + userLanguage + '.js')[userLanguage]`

this error occurs in the baseForm file.

**Comment by matejminar** [comment]
You can easily overwrite flatpickr's locale in `resources/js/admin/app-components/Form/AppForm.js`

The file could look something like this:

```
import { BaseForm } from 'craftable';

export default {
	mixins: [BaseForm],
	data: function() {
		return {
      datePickerConfig: {
        locale: require('flatpickr/dist/l10n/pt.js').Portuguese
      },
      timePickerConfig: {
        locale: require('flatpickr/dist/l10n/pt.js').Portuguese
      },
      datetimePickerConfig: {
        locale: require('flatpickr/dist/l10n/pt.js').Portuguese
      },
		}
	}
};
```

As you mentioned, Flatpickr supports only Portuguese, not Brazilian Portuguese.
However, you can easily create your own Brazilian Portuguese locale file and import that (take a look at `node_modules/flatpickr/dist/l10n/pt.js` to gain inspiration).

We have fixed the issue of js crashing when there is no flatpickr locale to import. We will just leave the default locale from now on and user can easily change to their preferred datetimepicker locale with the overwrite above.
