### ISSUE TITLE
craftable v1.1.3 error

### ISSUE THREAD

**Issue by ammonkc** [BRACKETS-by-TRIAD/craftable-frontend#3]
the v1.1.3 update seems to cause an error 

```
Uncaught ReferenceError: jQuery is not defined
``` 
It looks like the vue-trumbowyg package is causing it. I'm not sure why it can't find jQuery since equerry is being imported in `assets/admin/js/bootstrap.js`

**Comment by matejminar** [comment]
Thanks, I've hotfixed it in v1.1.4 and going to look at it in greater detail.
